"""Set up the private NVDA's settings for the tests of version 1.56 (issue 49): the tester's profiles, and a silent copy of
Eloquence64RS 19.1.4's driver. Test tooling, never shipped.

    python setup_issue49.py            the tester's profiles, the question about speech settings that differ is not asked
    python setup_issue49.py ask        the same, and the question is asked 20 seconds after NVDA starts
    python setup_issue49.py off        as the first, with the assistant's setting that keeps the voice's settings the same
                                       everywhere turned off: NVDA and Eloquence as the tester had them

The profiles are what NVDA's log shows the tester's as it loaded them (nvda.ini, JAWS - msedge.ini, browseMode.ini, ...). The
voice is "eloquence": Eloquence64RS's functions that keep and apply a copy of the voice's settings for each set of turned-on
profiles, and its SynthDriver's methods that load and save settings and set the pitch and volume, are the add-on's own, word for
word (tests/issue49Sources.py has them and says where from), so a real NVDA's profile switches, Settings dialog and settings ring
run into them as they do into the real driver. The engine is a table of numbers and the voice makes no sound, so nothing here
can be heard on the PC it runs on.
"""

import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, ".."))
import issue49Sources  # noqa: E402

CFG = os.path.join(HERE, "cfg")


def write(path, text):
	os.makedirs(os.path.dirname(path), exist_ok=True)
	with open(path, "w", encoding="utf-8", newline="\r\n") as stream:
		stream.write(text)


NVDA_INI_SPEECH = """[speech]
	synth = eloquence
	autoLanguageSwitching = False
	symbolLevel = 200
	[[eloquence]]
		voice = eloquence
		variant = 1
		pitch = 65
		inflection = 30
		volume = 100
		rgh = 0
		bth = 0
		rate = 65
		hsz = 50
		backquoteVoiceTags = False
		ABRDICT = False
		phrasePrediction = False
		pauseMode = 0
		audioQuality = standard
"""

PROFILES = {
	"JAWS - msedge": """schemaVersion = 24
[speech]
	autoLanguageSwitching = False
	[[eloquence]]
		volume = 80
[UIA]
	allowInMSWord = 0
""",
	"browseMode": """schemaVersion = 24
[mouse]
	enableMouseTracking = True
[documentFormatting]
	autoLanguageSwitching = True
[speech]
	[[eloquence]]
		volume = 100
[audio]
	audioDuckingMode = 0
""",
	"JAWS - 1password": """schemaVersion = 24
[keyboard]
	alertForSpellingErrors = False
""",
	"kitchen games": "schemaVersion = 24\n",
}

TRIGGERS = """[triggersToProfiles]
	app:msedge = JAWS - msedge
	app:1password = JAWS - 1password
"""

DRIVER = '''# Generated by setup_issue49.py: a silent test copy of Eloquence64RS 19.1.4-RS's profile handling, for the rig. Never shipped.
# The part between the two lines of dashes, and the methods of SynthDriver that come from the same file, are the add-on's own,
# word for word (tests/issue49Sources.py). The engine is a table of numbers and nothing is spoken.

import os
from collections import OrderedDict

import config
import globalVars
import synthDriverHandler
import wx
from logHandler import log
from speech.commands import IndexCommand

# ---------------------------------------------------------------------------------------------------------------------
{profiles}
# ---------------------------------------------------------------------------------------------------------------------


class _Engine:
	"""Eloquence's engine, as far as the driver's methods use it: a table of numbers."""

	rate = "rate"
	pitch = "pitch"
	vlm = "volume"
	eciPath = "C:\\\\Eloquence\\\\eci.dll"

	def __init__(self):
		self.params = {{"rate": 65, "pitch": 65, "volume": 100}}

	def getVParam(self, parameter):
		return self.params.get(parameter)

	def setVParam(self, parameter, value):
		self.params[parameter] = value

	def set_dictionary_directory(self, directory):
		pass


class _Dictionaries:
	def resolve_profile(self, conf, directory, migrate=False):
		return "standard"

	def active_directory(self, directory, profile):
		return directory


_eloquence = _Engine()
_eloquence_dictionaries = _Dictionaries()


class SynthDriver(synthDriverHandler.SynthDriver):
	name = "eloquence"
	description = "Eloquence (silent test copy of Eloquence64RS 19.1.4's profile handling)"
	supportedSettings = (
		synthDriverHandler.SynthDriver.RateSetting(),
		synthDriverHandler.SynthDriver.PitchSetting(),
		synthDriverHandler.SynthDriver.VolumeSetting(),
	)
	_availableVoices = OrderedDict({{name: synthDriverHandler.VoiceInfo(name, description)}})
	# The settings Eloquence64RS's driver has besides the rate, pitch and volume it keeps for each set of profiles: plain here.
	variant = "1"
	inflection = 30
	hsz = 50
	rgh = 0
	bth = 0
	backquoteVoiceTags = False
	ABRDICT = False
	phrasePrediction = False
	pauseMode = "0"
	audioQuality = "standard"

	@classmethod
	def check(cls):
		return True

	def __init__(self):
		# As Eloquence64RS's: construction and the settings NVDA loads next are one transaction.
		self._loading_profile_settings = True

	def speak(self, speechSequence):
		self.lastIndex = None
		for item in speechSequence:
			if isinstance(item, IndexCommand):
				self.lastIndex = item.index

	def cancel(self):
		self.lastIndex = None

	def _get_voice(self):
		return self.name

	def _set_voice(self, value):
		# Eloquence's voice numbers, such as the tester's 65536, are not names of voices here: the one voice stays.
		pass

	# The rate is a table entry here, as Eloquence64RS's is a conversion of one; it is kept for each set of profiles in the same way.
	def _get_rate(self):
		return self.getVParam(_eloquence.rate)

	def _set_rate(self, vl):
		self.setVParam(_eloquence.rate, int(vl))
		_remember_current_profile_setting(self, "rate", int(vl))

{methods}'''


def main():
	ask = "ask" in sys.argv[1:]
	off = "off" in sys.argv[1:]
	with open(os.path.join(HERE, "nvda.ini.sample"), encoding="utf-8") as stream:
		sample = stream.read()
	start = sample.index("[speech]")
	end = sample.index("[braille]")
	ini = sample[:start] + NVDA_INI_SPEECH + sample[end:]
	ini = ini.replace("\tsoundVolume = 0\n", "\tsoundVolume = 0\n\taudioDuckingMode = 0\n")
	write(os.path.join(CFG, "nvda.ini"), ini)
	for name, text in PROFILES.items():
		write(os.path.join(CFG, "profiles", name + ".ini"), text)
	write(os.path.join(CFG, "profileTriggers.ini"), TRIGGERS)
	write(os.path.join(CFG, "scratchpad", "synthDrivers", "eloquence.py"), DRIVER.format(profiles=issue49Sources.ELOQUENCE_PROFILES, methods=issue49Sources.ELOQUENCE_DRIVER_METHODS))
	state = {"welcomeShown": True, "checkForUpdatesAutomatically": False}
	if not ask:
		# The question that is asked once for these values: said to have been asked.
		state["evenSpeechAsked"] = ["eloquence.volume:JAWS - msedge=80|browseMode=100|normal configuration=100"]
	if off:
		state["keepSpeechEven"] = False
	write(os.path.join(CFG, "jawsMigrator", "state.json"), json.dumps(state, indent="\t"))
	os.makedirs(os.path.join(CFG, "scratchpad", "globalPlugins"), exist_ok=True)
	driver = os.path.join(CFG, "scratchpad", "globalPlugins", "aa47driver.py")
	with open(os.path.join(HERE, "aa47driver.py"), "rb") as source, open(driver, "wb") as target:
		target.write(source.read())
	print("set up", CFG, "(the question is asked)" if ask else "(the question is not asked)", "(kept the same everywhere: off)" if off else "")


if __name__ == "__main__":
	main()
