# JAWS Migration Assistant for NVDA
# Copyright (C) 2026 Josh Kennedy
# This file is covered by the GNU General Public License, version 2 or later.

"""Data for translating JAWS keyboard assignments (.jkm files) into NVDA input gestures.

Contents:

- ``KEY_NAMES``: JAWS key token (lower case) -> NVDA key name as used in gesture identifiers.
- ``JAWS_MODIFIER_TOKENS``: JAWS tokens that mean the screen reader key (JAWSKey, Insert, CapsLock...).
- ``UNSUPPORTED_KEY_TOKENS``: JAWS tokens with no NVDA keyboard equivalent
  (HomeRow, MAGic keyboard keys, mouse buttons).
- ``jawsKeyToNvdaGesture()``: converts the left side of a .jkm line into an NVDA gesture identifier.
- ``DEFAULT_JKM_SECTIONS``: which .jkm sections hold convertible keyboard bindings, and their layout.
- ``SCRIPT_MAP`` / ``QUICK_NAV_MAP``: JAWS script name -> ``(module, class, script, description)``
  of a functionally equivalent NVDA script. ``COMMAND_KEY_TARGETS`` replaces a quick navigation target
  for keystrokes that are not quick navigation keys. ``ADDITIONAL_TARGETS`` can list extra classes for
  a command. ``getNvdaTargets()`` looks a JAWS script up in all of them.
- ``SENDS_KEYSTROKE_CLASSES`` / ``SENDS_KEYSTROKE_SCRIPTS``: NVDA scripts that pass the pressed
  keystroke on to the application. No map may point at them; ``getNvdaTargets()`` drops them.
- ``PASSTHROUGH_SCRIPTS`` / ``isPassThroughBinding()``: JAWS scripts that only pass a standard Windows
  key through and speak the result. NVDA does this natively, so these bindings need no NVDA gesture.
- ``isQuickNavKey()``: whether a keystroke is a browse mode quick navigation key (a letter, digit or
  punctuation key, alone or with Shift).
- ``parseJkm()`` / ``readJkmFile()``: a small .jkm reader.

Every NVDA target was checked against the NVDA 2026.2 source: a ``script_<name>`` method on that
class, or a quick navigation script generated by ``BrowseModeTreeInterceptor.addQuickNav``.
The maps only list commands with the same user-visible effect in NVDA. Where the effect differs
slightly, the description says how.

Limitations:

- Layered keys (``JAWSKey+Space&T&...``, ``&`` means a key sequence), braille, touch and mouse
  bindings cannot be expressed as NVDA keyboard gestures, so they convert to ``None``.
- JAWSKey, Insert and CapsLock all become ``NVDA``. NVDA cannot tell which NVDA key was pressed,
  so in [Laptop Keys] ``Insert+H`` (HotKeyHelp) and ``JAWSKey+H`` (CapsLock+H, SaySentence) produce
  the same gesture. Where Caps Lock is the JAWS key (the Laptop layout), ``keyPlan.planKeys`` lets the
  JAWSKey/CapsLock keystroke decide what the NVDA gesture does, even when NVDA has no equivalent for it.
- JAWS separates numpad arrows (``UpArrow``) from the dedicated cursor keys (``ExtendedUpArrow``).
  Both become NVDA's dedicated key names (``upArrow``, ``home``, ...). No ``numpad8``-style
  alternatives are generated.
- NVDA names punctuation keys by the character they type. The names here assume a US English
  keyboard layout (``;``, ``'``, ``[``, ``/`` ...).
- Scripts are matched by name. Application keymaps can give a script name an application-specific
  meaning, so the maps are most reliable for Default.JKM.
- An NVDA script only runs where its class is in use. ``globalCommands`` targets work everywhere;
  most others (find, table navigation, quick navigation, refresh) work in browse mode documents.
"""

# Tokens that mean "the screen reader key" when used as a modifier. JAWSKey is Insert in the desktop
# layout and CapsLock in the laptop layout. Insert and CapsLock can also be written explicitly.
# NumInsert and ExtInsert are the numpad and extended Insert keys from JAWS's [Modifiers] section.
JAWS_MODIFIER_TOKENS = frozenset(
	{
		"jawskey",
		"insert",
		"capslock",
		"numinsert",
		"extinsert",
	},
)

# NVDA modifier names, in the order they are written in generated identifiers.
NVDA_MODIFIER_ORDER = ("NVDA", "control", "alt", "shift", "windows")

# NVDA key names of numpad keys (NumLock off), as NVDA's vkCodes module names them.
NUMPAD_KEY_NAMES = frozenset(
	{
		"numpad5",
		"numpadPlus",
		"numpadMinus",
		"numpadMultiply",
		"numpadDivide",
		"numpadEnter",
	},
)

# When True, gestures containing a numpad key and converted from a layout-neutral section get the
# kb(desktop): prefix, because most laptops have no numpad. NVDA's own numpad gestures use kb:, so set
# this to False to keep numpad bindings active in NVDA's laptop layout too.
NUMPAD_KEYS_ARE_DESKTOP_ONLY = True

# JAWS key token (lower case, spaces removed) -> NVDA key name.
# Names match NVDA's vkCodes.byCode and keyboardHandler (NVDA 2026.2).
KEY_NAMES = {
	# Screen reader key.
	"jawskey": "NVDA",
	"insert": "NVDA",
	"capslock": "NVDA",
	"numinsert": "NVDA",
	"extinsert": "NVDA",
	# Standard modifiers. NVDA generalizes left and right variants.
	"control": "control",
	"ctrl": "control",
	"leftcontrol": "control",
	"rightcontrol": "control",
	"leftctrl": "control",
	"rightctrl": "control",
	"alt": "alt",
	"leftalt": "alt",
	"rightalt": "alt",
	"shift": "shift",
	"leftshift": "shift",
	"rightshift": "shift",
	"windows": "windows",
	"leftwindows": "windows",
	"rightwindows": "windows",
	# Cursor keys. JAWS "Extended" names are the dedicated cursor pad; plain names are
	# the numpad keys with NumLock off. Both map to NVDA's dedicated key names.
	"uparrow": "upArrow",
	"downarrow": "downArrow",
	"leftarrow": "leftArrow",
	"rightarrow": "rightArrow",
	"home": "home",
	"end": "end",
	"pageup": "pageUp",
	"pagedown": "pageDown",
	"delete": "delete",
	"extendeduparrow": "upArrow",
	"extendeddownarrow": "downArrow",
	"extendedleftarrow": "leftArrow",
	"extendedrightarrow": "rightArrow",
	"extendedhome": "home",
	"extendedend": "end",
	"extendedpageup": "pageUp",
	"extendedpagedown": "pageDown",
	"extendeddelete": "delete",
	# Numpad (NumLock off).
	"numpad5": "numpad5",
	"numpadplus": "numpadPlus",
	"numpadminus": "numpadMinus",
	"numpadstar": "numpadMultiply",
	"numpadslash": "numpadDivide",
	"numpadenter": "numpadEnter",
	# Other named keys.
	"enter": "enter",
	"escape": "escape",
	"tab": "tab",
	"space": "space",
	"spacebar": "space",
	"backspace": "backspace",
	"applications": "applications",
	"printscreen": "printScreen",
	"scrolllock": "scrollLock",
	# Punctuation (US layout). NVDA uses the character the key types.
	"comma": ",",
	",": ",",
	"period": ".",
	".": ".",
	"semicolon": ";",
	";": ";",
	"apostrophe": "'",
	"'": "'",
	"slash": "/",
	"/": "/",
	"backslash": "\\",
	"\\": "\\",
	"leftbracket": "[",
	"[": "[",
	"rightbracket": "]",
	"]": "]",
	"dash": "-",
	"-": "-",
	"equals": "=",
	"=": "=",
	"grave": "`",
	"graveaccent": "`",
	"`": "`",
}
# Letters, digits and function keys.
KEY_NAMES.update({chr(c): chr(c) for c in range(ord("a"), ord("z") + 1)})
KEY_NAMES.update({str(d): str(d) for d in range(10)})
KEY_NAMES.update({f"f{n}": f"f{n}" for n in range(1, 25)})

# JAWS tokens that appear in keyboard sections but have no NVDA keyboard equivalent.
UNSUPPORTED_KEY_TOKENS = frozenset(
	{
		# JAWS script utility (HomeRow) mode prefix.
		"homerow",
		# Special keys on the MAGic large-print keyboard.
		"mkdecreaserate",
		"mkincreaserate",
		"mkkeyboardecho",
		"mklaunchmagic",
		"mklinkslist",
		"mkmouseecho",
		"mkresearchit",
		"mkspeechtoggle",
		"mktextviewer",
		# Mouse buttons.
		"mouseleftclick",
		"leftmousebutton",
		"rightmousebutton",
	},
)

# .jkm section name (lower case) -> what the section's bindings mean for conversion:
# "common", "desktop" or "laptop": keyboard bindings for that JAWS layout.
# "browse": keyboard bindings that JAWS only uses with the virtual cursor, which is NVDA's browse mode.
# The keys convert like "common" ones; bind them on the target's own class (see getNvdaTargets).
# None: not converted. Unlisted sections, such as the braille display sections, are also None.
DEFAULT_JKM_SECTIONS = {
	"common keys": "common",
	"desktop keys": "desktop",
	"laptop keys": "laptop",
	"quick navigation keys": "browse",
	"virtual keys": "browse",
	# JAWS Tandem remote support; NVDA has Remote Access equivalents.
	"tandem keys": "common",
	# The Classic Laptop (older Alt+letter) and Kinesis keyboard layouts: converted only when the
	# user chooses those layouts. keyPlan.keyboardLayouts finds every layout a key map has.
	"classic laptop keys": None,
	"kinesis keys": None,
	# Keyboard sections that are deliberately not converted.
	# Only active during Say All (PageUp/PageDown change the rate); NVDA has no Say All key context.
	"sayall keys": None,
	# Only active in the JAWS touch cursor / object navigation modes; they rebind arrows and letters.
	"touchnavigation keys": None,
	"touchnavigation laptop keys": None,
	"objectnavigation keys": None,
	"objectnavigation laptop keys": None,
	"object quick navigation keys": None,
	"objecttextreview keys": None,
	# Retired assignments kept for reference.
	"old keys": None,
	# Sections that hold settings or data, not bindings.
	"quick navigation keys manager data": None,
	"speech on demand": None,
	"key name translations": None,
	"keyboard layouts": None,
	"modifiers": None,
	"desktop modifiers": None,
	"laptop modifiers": None,
	"classic laptop modifiers": None,
	"kinesis modifiers": None,
	"magic modifiers": None,
	"pac mate modifiers": None,
}


def getSectionLayout(sectionName: str) -> str | None:
	"""Return the DEFAULT_JKM_SECTIONS value for a .jkm section name (any case), or None."""
	return DEFAULT_JKM_SECTIONS.get(sectionName.strip().lower())


def _convertKey(jawsKey: str, layout: str | None) -> tuple[str | None, str | None]:
	"""Convert a JAWS key to an NVDA gesture identifier.
	:return: ``(gesture, None)`` on success, or ``(None, reason)`` where reason is one of
		"empty", "layered", "braille", "modifierOnly", "unsupportedKey", "unknownKey" or "badModifier".
	"""
	key = (jawsKey or "").strip()
	if key.endswith("*"):
		key = key[:-1].rstrip()
	if not key:
		return None, "empty"
	if "&" in key:
		return None, "layered"
	if key.lower().startswith("braille"):
		return None, "braille"
	tokens = [t.replace(" ", "").lower() for t in key.split("+")]
	for token in tokens:
		if token in UNSUPPORTED_KEY_TOKENS:
			return None, "unsupportedKey"
		if token not in KEY_NAMES:
			return None, "unknownKey"
	modifiers = set()
	for token in tokens[:-1]:
		name = KEY_NAMES[token]
		if name not in NVDA_MODIFIER_ORDER:
			# For example ScrollLock used as a modifier, which NVDA does not support.
			return None, "badModifier"
		modifiers.add(name)
	mainToken = tokens[-1]
	mainKey = KEY_NAMES[mainToken]
	if mainToken in JAWS_MODIFIER_TOKENS or mainKey in NVDA_MODIFIER_ORDER:
		# Modifier-only chords (JAWSKey alone, Alt+Shift) cannot be bound to NVDA scripts.
		return None, "modifierOnly"
	keyNames = [m for m in NVDA_MODIFIER_ORDER if m in modifiers]
	keyNames.append(mainKey)
	layout = (layout or "common").lower()
	if layout in ("desktop", "laptop"):
		# Bindings from layout-specific sections only exist in that JAWS layout.
		prefix = f"kb({layout}):"
	elif "capslock" in tokens[:-1]:
		# CapsLock is only the JAWS key in the laptop layout.
		prefix = "kb(laptop):"
	elif NUMPAD_KEYS_ARE_DESKTOP_ONLY and mainKey in NUMPAD_KEY_NAMES:
		prefix = "kb(desktop):"
	else:
		prefix = "kb:"
	return prefix + "+".join(keyNames), None


def jawsKeyToNvdaGesture(jawsKey: str, layout: str) -> str | None:
	"""Convert one JAWS key (the left side of a .jkm line) to an NVDA gesture identifier.

	:param jawsKey: For example ``"JAWSKey+Shift+2"``, ``"Alt+Control+NumPad5"`` or ``"H"``.
		A trailing ``*`` is ignored.
	:param layout: ``"common"``, ``"desktop"`` or ``"laptop"`` (the section's value in
		DEFAULT_JKM_SECTIONS). ``"browse"`` and anything else are treated as ``"common"``.
	:return: For example ``"kb:NVDA+shift+2"`` or ``"kb(laptop):NVDA+i"``. None for layered keys,
		braille, touch or mouse keys, modifier-only chords and keys with unknown tokens.
	"""
	return _convertKey(jawsKey, layout)[0]


def isQuickNavKey(jawsKey: str) -> bool:
	"""True for a browse mode quick navigation key: a letter, digit or punctuation key, alone or with Shift.

	In browse mode only these keys may take over NVDA's own quick navigation letters without asking.
	Other keystrokes in [virtual keys], such as ``Control+JAWSKey+R``, are commands like any other.
	"""
	gesture = _convertKey(jawsKey, "common")[0]
	if gesture is None:
		return False
	keys = gesture.split(":", 1)[1].split("+")
	return len(keys[-1]) == 1 and all(key == "shift" for key in keys[:-1])


def normalizeScriptName(scriptName: str) -> str:
	"""Lower-case a .jkm script reference and drop its arguments.
	For example ``"SpeakPlaceMarkerN(1)"`` becomes ``"speakplacemarkern"``.
	"""
	name = scriptName.strip()
	paren = name.find("(")
	if paren != -1:
		name = name[:paren]
	return name.strip().lower()


# JAWS script name (lower case) -> (NVDA module, class, script name, description of the NVDA command).
SCRIPT_MAP = {
	# Reading.
	"sayline": (
		"globalCommands",
		"GlobalCommands",
		"reportCurrentLine",
		"Report the current line; twice spells it, three times spells it phonetically",
	),
	"sayall": (
		"globalCommands",
		"GlobalCommands",
		"sayAll",
		"Read from the caret to the end of the text, moving the caret",
	),
	"sayword": (
		"globalCommands",
		"GlobalCommands",
		"review_currentWord",
		"Report the word at the review cursor, which follows the caret by default; twice spells it",
	),
	"saycharacter": (
		"globalCommands",
		"GlobalCommands",
		"review_currentCharacter",
		"Report the character at the review cursor; twice phonetically, three times its character code",
	),
	"sayselectedtext": (
		"globalCommands",
		"GlobalCommands",
		"reportCurrentSelection",
		"Report the selected text",
	),
	"saynextsentence": (
		"cursorManager",
		"CursorManager",
		"moveBySentence_forward",
		"Move to the next sentence and read it (browse mode documents)",
	),
	"saypriorsentence": (
		"cursorManager",
		"CursorManager",
		"moveBySentence_back",
		"Move to the previous sentence and read it (browse mode documents)",
	),
	# Window, focus and formatting information.
	"saywindowtitle": (
		"globalCommands",
		"GlobalCommands",
		"title",
		"Report the title of the foreground window; twice spells it, three times copies it",
	),
	"saytoplineofwindow": (
		"globalCommands",
		"GlobalCommands",
		"title",
		"Report the foreground window's title (JAWS reads the window's top line, which is normally the title)",
	),
	"saybottomlineofwindow": (
		"globalCommands",
		"GlobalCommands",
		"reportStatusLine",
		"Read the application's status bar; twice spells it, three times copies it",
	),
	"saywindowpromptandtext": (
		"globalCommands",
		"GlobalCommands",
		"reportCurrentFocus",
		"Report the focused control with its label, type and value; twice spells it",
	),
	"readboxintaborder": (
		"globalCommands",
		"GlobalCommands",
		"speakForeground",
		"Read all controls in the active window or dialog",
	),
	"saycurrentaccesskey": (
		"globalCommands",
		"GlobalCommands",
		"reportFocusObjectAccelerator",
		"Report the shortcut (access) key of the focused control",
	),
	"sayactivecursor": (
		"globalCommands",
		"GlobalCommands",
		"caretPos_currentDimensions",
		"Report the location of the text or object at the caret; twice gives more detail",
	),
	"sayfont": (
		"globalCommands",
		"GlobalCommands",
		"reportOrShowFormattingAtCaret",
		"Report the font and formatting at the caret; twice shows it in a browseable window",
	),
	"indicatelinksourceurl": (
		"globalCommands",
		"GlobalCommands",
		"reportLinkDestination",
		"Report the URL of the link at the caret or focus; twice shows it in a window",
	),
	"scriptfilename": (
		"globalCommands",
		"GlobalCommands",
		"reportAppModuleInfo",
		"Report the active program's executable and the NVDA app module loaded for it",
	),
	# System information.
	"saysystemtime": (
		"globalCommands",
		"GlobalCommands",
		"dateTime",
		"Report the current time; twice reports the date",
	),
	"saybatterylevel": (
		"globalCommands",
		"GlobalCommands",
		"say_battery_status",
		"Report battery charge, power source and time remaining",
	),
	"sayclipboard": (
		"globalCommands",
		"GlobalCommands",
		"reportClipboardText",
		"Report the text on the clipboard; twice spells it",
	),
	# Speech and verbosity.
	"setpunctuationlevel": (
		"globalCommands",
		"GlobalCommands",
		"cycleSpeechSymbolLevel",
		"Cycle the symbol (punctuation) level: none, some, most, all, character",
	),
	"settypingecho": (
		"globalCommands",
		"GlobalCommands",
		"toggleSpeakTypedCharacters",
		"Cycle when typed characters are spoken (typed words have their own command, NVDA+3)",
	),
	"setscreenecho": (
		"globalCommands",
		"GlobalCommands",
		"toggleReportDynamicContentChanges",
		"Toggle reporting of dynamic content changes, such as new console text and live regions",
	),
	"increasevoiceratetemporary": (
		"globalCommands",
		"GlobalCommands",
		"increaseSynthSetting",
		"Increase the current synth settings ring setting (the voice rate unless the ring was moved)",
	),
	"increasevoiceratepermanent": (
		"globalCommands",
		"GlobalCommands",
		"increaseSynthSetting",
		"Increase the current synth settings ring setting (the voice rate unless the ring was moved)",
	),
	"decreasevoiceratetemporary": (
		"globalCommands",
		"GlobalCommands",
		"decreaseSynthSetting",
		"Decrease the current synth settings ring setting (the voice rate unless the ring was moved)",
	),
	"decreasevoiceratepermanent": (
		"globalCommands",
		"GlobalCommands",
		"decreaseSynthSetting",
		"Decrease the current synth settings ring setting (the voice rate unless the ring was moved)",
	),
	"mutesynthesizer": (
		"globalCommands",
		"GlobalCommands",
		"speechMode",
		"Cycle speech modes (talk, on-demand, beeps, off) to silence or restore speech",
	),
	"speechondemandtoggle": (
		"globalCommands",
		"GlobalCommands",
		"speechMode",
		"Cycle speech modes (talk, on-demand, beeps, off) to silence or restore speech",
	),
	"toggleaudioducking": (
		"globalCommands",
		"GlobalCommands",
		"cycleAudioDuckingMode",
		"Cycle audio ducking modes (whether other audio is lowered while NVDA speaks)",
	),
	"mouseechotoggle": (
		"globalCommands",
		"GlobalCommands",
		"toggleMouseTracking",
		"Toggle reporting of the text and objects under the mouse as it moves",
	),
	"togglemouseechofromlayer": (
		"globalCommands",
		"GlobalCommands",
		"toggleMouseTracking",
		"Toggle reporting of the text and objects under the mouse as it moves",
	),
	# Cursors and mouse. NVDA's review cursor and navigator object play the JAWS cursor's role.
	"routejawscursortopc": (
		"globalCommands",
		"GlobalCommands",
		"navigatorObject_toFocus",
		"Move the review cursor and navigator object to the focus and caret"
		" (NVDA+numpadDivide then moves the mouse there)",
	),
	"routepccursortojaws": (
		"globalCommands",
		"GlobalCommands",
		"navigatorObject_moveFocus",
		"Move focus to the navigator object; twice moves the caret to the review cursor",
	),
	"tetherjawstopc": (
		"globalCommands",
		"GlobalCommands",
		"toggleCaretMovesReviewCursor",
		"Toggle whether the review cursor follows the system caret",
	),
	"leftmousebutton": (
		"globalCommands",
		"GlobalCommands",
		"leftMouseClick",
		"Click the left mouse button at the mouse pointer",
	),
	"rightmousebutton": (
		"globalCommands",
		"GlobalCommands",
		"rightMouseClick",
		"Click the right mouse button at the mouse pointer",
	),
	"leftmousebuttonlock": (
		"globalCommands",
		"GlobalCommands",
		"toggleLeftMouseButton",
		"Lock or unlock the left mouse button, for dragging",
	),
	"rightmousebuttonlock": (
		"globalCommands",
		"GlobalCommands",
		"toggleRightMouseButton",
		"Lock or unlock the right mouse button",
	),
	# Virtual cursor (browse mode).
	"virtualpccursortoggle": (
		"globalCommands",
		"GlobalCommands",
		"toggleVirtualBufferPassThrough",
		"Toggle between browse mode and focus mode",
	),
	"refreshscreen": (
		"virtualBuffers",
		"VirtualBuffer",
		"refreshBuffer",
		"Refresh the browse mode document content",
	),
	"quicknavigationkeyssuspendorresume": (
		"browseMode",
		"BrowseModeTreeInterceptor",
		"toggleSingleLetterNav",
		"Toggle single letter (quick key) navigation in browse mode",
	),
	"selectalink": (
		"browseMode",
		"BrowseModeTreeInterceptor",
		"elementsList",
		"Open the Elements List (links, headings, form fields, buttons, landmarks)",
	),
	"selectaheading": (
		"browseMode",
		"BrowseModeTreeInterceptor",
		"elementsList",
		"Open the Elements List (links, headings, form fields, buttons, landmarks)",
	),
	"selectaformfield": (
		"browseMode",
		"BrowseModeTreeInterceptor",
		"elementsList",
		"Open the Elements List (links, headings, form fields, buttons, landmarks)",
	),
	"selectabuttonformfield": (
		"browseMode",
		"BrowseModeTreeInterceptor",
		"elementsList",
		"Open the Elements List (links, headings, form fields, buttons, landmarks)",
	),
	"selectaregion": (
		"browseMode",
		"BrowseModeTreeInterceptor",
		"elementsList",
		"Open the Elements List; its Landmarks list shows the page regions",
	),
	"jawsfind": (
		"cursorManager",
		"CursorManager",
		"find",
		"Search for text in the current document",
	),
	"jawsfindnext": (
		"cursorManager",
		"CursorManager",
		"findNext",
		"Find the next occurrence of the last searched text",
	),
	"jawsfindprior": (
		"cursorManager",
		"CursorManager",
		"findPrevious",
		"Find the previous occurrence of the last searched text",
	),
	# Tables.
	"priorcell": (
		"documentBase",
		"DocumentWithTableNavigation",
		"previousColumn",
		"Move to the previous cell in the row",
	),
	"nextcell": (
		"documentBase",
		"DocumentWithTableNavigation",
		"nextColumn",
		"Move to the next cell in the row",
	),
	"upcell": (
		"documentBase",
		"DocumentWithTableNavigation",
		"previousRow",
		"Move to the cell above in the column",
	),
	"downcell": (
		"documentBase",
		"DocumentWithTableNavigation",
		"nextRow",
		"Move to the cell below in the column",
	),
	"movetostartofrow": (
		"documentBase",
		"DocumentWithTableNavigation",
		"firstColumn",
		"Move to the first cell in the row",
	),
	"movetoendofrow": (
		"documentBase",
		"DocumentWithTableNavigation",
		"lastColumn",
		"Move to the last cell in the row",
	),
	"movetotopofcolumn": (
		"documentBase",
		"DocumentWithTableNavigation",
		"firstRow",
		"Move to the first cell in the column",
	),
	"movetobottomofcolumn": (
		"documentBase",
		"DocumentWithTableNavigation",
		"lastRow",
		"Move to the last cell in the column",
	),
	"readcurrentrow": (
		"documentBase",
		"DocumentWithTableNavigation",
		"speakRow",
		"Read the current row from left to right without moving",
	),
	"readcurrentcolumn": (
		"documentBase",
		"DocumentWithTableNavigation",
		"speakColumn",
		"Read the current column from top to bottom without moving",
	),
	"readfromcurrentcell": (
		"documentBase",
		"DocumentWithTableNavigation",
		"sayAllRow",
		"Read the row from the current cell to the last cell",
	),
	"readtobottomofcolumn": (
		"documentBase",
		"DocumentWithTableNavigation",
		"sayAllColumn",
		"Read the column from the current cell down to the last cell",
	),
	# Help, settings and tools.
	"keyboardhelp": (
		"globalCommands",
		"GlobalCommands",
		"toggleInputHelp",
		"Toggle input help: pressed keys are described instead of performed",
	),
	"hotkeyhelp": (
		"globalCommands",
		"GlobalCommands",
		"activateInputGesturesDialog",
		"Open the Input Gestures dialog, which lists NVDA's commands and their keystrokes",
	),
	"keyboardmanager": (
		"globalCommands",
		"GlobalCommands",
		"activateInputGesturesDialog",
		"Open the Input Gestures dialog to view and reassign keystrokes",
	),
	"passkeythrough": (
		"globalCommands",
		"GlobalCommands",
		"passNextKeyThrough",
		"Pass the next key straight through to the application",
	),
	"jawswindow": (
		"globalCommands",
		"GlobalCommands",
		"showGui",
		"Open the NVDA menu",
	),
	"runjawsmanager": (
		"globalCommands",
		"GlobalCommands",
		"showGui",
		"Open the NVDA menu, whose Preferences and Tools submenus hold NVDA's settings and tools",
	),
	"settingscenter": (
		"globalCommands",
		"GlobalCommands",
		"activateGeneralSettingsDialog",
		"Open the NVDA Settings dialog",
	),
	"dictionarymanager": (
		"globalCommands",
		"GlobalCommands",
		"activateDefaultDictionaryDialog",
		"Open the default speech dictionary to add or change pronunciations",
	),
	"shutdownjaws": (
		"globalCommands",
		"GlobalCommands",
		"quit",
		"Exit NVDA",
	),
	"restartwithoutdump": (
		"globalCommands",
		"GlobalCommands",
		"restart",
		"Restart NVDA",
	),
	"refreshscripts": (
		"globalCommands",
		"GlobalCommands",
		"reloadPlugins",
		"Reload app modules and global plugins without restarting NVDA",
	),
	"screenshadetoggle": (
		"globalCommands",
		"GlobalCommands",
		"toggleScreenCurtain",
		"Toggle the screen curtain, which blacks out the screen",
	),
	"toggletextviewerenable": (
		"globalCommands",
		"GlobalCommands",
		"toggleSpeechViewer",
		"Toggle the Speech Viewer window, which shows the text NVDA speaks",
	),
	"togglebrailleviewerenable": (
		"globalCommands",
		"GlobalCommands",
		"toggleBrailleViewer",
		"Toggle the Braille Viewer window",
	),
	"recognizecontrol": (
		"globalCommands",
		"GlobalCommands",
		"recognizeWithUwpOcr",
		"Recognize the navigator object's content (the focus by default) with Windows OCR",
	),
	# JAWS Tandem -> NVDA Remote Access.
	"startorendtandemsession": (
		"globalCommands",
		"GlobalCommands",
		"toggleRemoteConnection",
		"Connect to or disconnect from a Remote Access session",
	),
	"toggletandemmode": (
		"globalCommands",
		"GlobalCommands",
		"sendKeys",
		"Switch whether the keyboard controls the local or the remote computer",
	),
}

# JAWS navigation quick key scripts ([Quick Navigation Keys] and the Quick Navigation Keys Manager list)
# -> browse mode quick navigation scripts. The next/previous scripts are generated by
# BrowseModeTreeInterceptor.addQuickNav in NVDA's browseMode module.
QUICK_NAV_MAP = {
	"movetonextheading": ("browseMode", "BrowseModeTreeInterceptor", "nextHeading", "Move to the next heading"),
	"movetopriorheading": (
		"browseMode",
		"BrowseModeTreeInterceptor",
		"previousHeading",
		"Move to the previous heading",
	),
	"movetonextheadinglevelone": (
		"browseMode",
		"BrowseModeTreeInterceptor",
		"nextHeading1",
		"Move to the next heading at level 1",
	),
	"movetopriorheadinglevelone": (
		"browseMode",
		"BrowseModeTreeInterceptor",
		"previousHeading1",
		"Move to the previous heading at level 1",
	),
	"movetonextheadingleveltwo": (
		"browseMode",
		"BrowseModeTreeInterceptor",
		"nextHeading2",
		"Move to the next heading at level 2",
	),
	"movetopriorheadingleveltwo": (
		"browseMode",
		"BrowseModeTreeInterceptor",
		"previousHeading2",
		"Move to the previous heading at level 2",
	),
	"movetonextheadinglevelthree": (
		"browseMode",
		"BrowseModeTreeInterceptor",
		"nextHeading3",
		"Move to the next heading at level 3",
	),
	"movetopriorheadinglevelthree": (
		"browseMode",
		"BrowseModeTreeInterceptor",
		"previousHeading3",
		"Move to the previous heading at level 3",
	),
	"movetonextheadinglevelfour": (
		"browseMode",
		"BrowseModeTreeInterceptor",
		"nextHeading4",
		"Move to the next heading at level 4",
	),
	"movetopriorheadinglevelfour": (
		"browseMode",
		"BrowseModeTreeInterceptor",
		"previousHeading4",
		"Move to the previous heading at level 4",
	),
	"movetonextheadinglevelfive": (
		"browseMode",
		"BrowseModeTreeInterceptor",
		"nextHeading5",
		"Move to the next heading at level 5",
	),
	"movetopriorheadinglevelfive": (
		"browseMode",
		"BrowseModeTreeInterceptor",
		"previousHeading5",
		"Move to the previous heading at level 5",
	),
	"movetonextheadinglevelsix": (
		"browseMode",
		"BrowseModeTreeInterceptor",
		"nextHeading6",
		"Move to the next heading at level 6",
	),
	"movetopriorheadinglevelsix": (
		"browseMode",
		"BrowseModeTreeInterceptor",
		"previousHeading6",
		"Move to the previous heading at level 6",
	),
	"movetonexttable": ("browseMode", "BrowseModeTreeInterceptor", "nextTable", "Move to the next table"),
	"movetopriortable": (
		"browseMode",
		"BrowseModeTreeInterceptor",
		"previousTable",
		"Move to the previous table",
	),
	"movetoanynextlink": ("browseMode", "BrowseModeTreeInterceptor", "nextLink", "Move to the next link"),
	"movetoanypriorlink": (
		"browseMode",
		"BrowseModeTreeInterceptor",
		"previousLink",
		"Move to the previous link",
	),
	"movetonextunvisitedlink": (
		"browseMode",
		"BrowseModeTreeInterceptor",
		"nextUnvisitedLink",
		"Move to the next unvisited link",
	),
	"movetopriorunvisitedlink": (
		"browseMode",
		"BrowseModeTreeInterceptor",
		"previousUnvisitedLink",
		"Move to the previous unvisited link",
	),
	"movetonextvisitedlink": (
		"browseMode",
		"BrowseModeTreeInterceptor",
		"nextVisitedLink",
		"Move to the next visited link",
	),
	"movetopriorvisitedlink": (
		"browseMode",
		"BrowseModeTreeInterceptor",
		"previousVisitedLink",
		"Move to the previous visited link",
	),
	"focustonextfield": (
		"browseMode",
		"BrowseModeTreeInterceptor",
		"nextFormField",
		"Move to the next form field",
	),
	"focustopriorfield": (
		"browseMode",
		"BrowseModeTreeInterceptor",
		"previousFormField",
		"Move to the previous form field",
	),
	"movetonextlist": ("browseMode", "BrowseModeTreeInterceptor", "nextList", "Move to the next list"),
	"movetopriorlist": ("browseMode", "BrowseModeTreeInterceptor", "previousList", "Move to the previous list"),
	"movetonextlistitem": (
		"browseMode",
		"BrowseModeTreeInterceptor",
		"nextListItem",
		"Move to the next list item",
	),
	"movetopriorlistitem": (
		"browseMode",
		"BrowseModeTreeInterceptor",
		"previousListItem",
		"Move to the previous list item",
	),
	"movetonextbutton": ("browseMode", "BrowseModeTreeInterceptor", "nextButton", "Move to the next button"),
	"movetopriorbutton": (
		"browseMode",
		"BrowseModeTreeInterceptor",
		"previousButton",
		"Move to the previous button",
	),
	"movetonextedit": ("browseMode", "BrowseModeTreeInterceptor", "nextEdit", "Move to the next edit field"),
	"movetoprioredit": (
		"browseMode",
		"BrowseModeTreeInterceptor",
		"previousEdit",
		"Move to the previous edit field",
	),
	"movetonextframe": ("browseMode", "BrowseModeTreeInterceptor", "nextFrame", "Move to the next frame"),
	"movetopriorframe": (
		"browseMode",
		"BrowseModeTreeInterceptor",
		"previousFrame",
		"Move to the previous frame",
	),
	"movetonextseparator": (
		"browseMode",
		"BrowseModeTreeInterceptor",
		"nextSeparator",
		"Move to the next separator",
	),
	"movetopriorseparator": (
		"browseMode",
		"BrowseModeTreeInterceptor",
		"previousSeparator",
		"Move to the previous separator",
	),
	"movetonextradiobutton": (
		"browseMode",
		"BrowseModeTreeInterceptor",
		"nextRadioButton",
		"Move to the next radio button",
	),
	"movetopriorradiobutton": (
		"browseMode",
		"BrowseModeTreeInterceptor",
		"previousRadioButton",
		"Move to the previous radio button",
	),
	"movetonextcombo": (
		"browseMode",
		"BrowseModeTreeInterceptor",
		"nextComboBox",
		"Move to the next combo box",
	),
	"movetopriorcombo": (
		"browseMode",
		"BrowseModeTreeInterceptor",
		"previousComboBox",
		"Move to the previous combo box",
	),
	"movetonextcheckbox": (
		"browseMode",
		"BrowseModeTreeInterceptor",
		"nextCheckBox",
		"Move to the next check box",
	),
	"movetopriorcheckbox": (
		"browseMode",
		"BrowseModeTreeInterceptor",
		"previousCheckBox",
		"Move to the previous check box",
	),
	"movetonextgraphic": ("browseMode", "BrowseModeTreeInterceptor", "nextGraphic", "Move to the next graphic"),
	"movetopriorgraphic": (
		"browseMode",
		"BrowseModeTreeInterceptor",
		"previousGraphic",
		"Move to the previous graphic",
	),
	"movetonextblockquote": (
		"browseMode",
		"BrowseModeTreeInterceptor",
		"nextBlockQuote",
		"Move to the next block quote",
	),
	"movetopriorblockquote": (
		"browseMode",
		"BrowseModeTreeInterceptor",
		"previousBlockQuote",
		"Move to the previous block quote",
	),
	"movetonextnonlinktext": (
		"browseMode",
		"BrowseModeTreeInterceptor",
		"nextNotLinkBlock",
		"Skip forward past a block of links to the next text",
	),
	"movetopriornonlinktext": (
		"browseMode",
		"BrowseModeTreeInterceptor",
		"previousNotLinkBlock",
		"Skip backward past a block of links to the previous text",
	),
	"movetonextregion": (
		"browseMode",
		"BrowseModeTreeInterceptor",
		"nextLandmark",
		"Move to the next landmark (region)",
	),
	"movetopriorregion": (
		"browseMode",
		"BrowseModeTreeInterceptor",
		"previousLandmark",
		"Move to the previous landmark (region)",
	),
	"movetonextarticle": ("browseMode", "BrowseModeTreeInterceptor", "nextArticle", "Move to the next article"),
	"movetopriorarticle": (
		"browseMode",
		"BrowseModeTreeInterceptor",
		"previousArticle",
		"Move to the previous article",
	),
	"movetonexttab": ("browseMode", "BrowseModeTreeInterceptor", "nextTab", "Move to the next tab"),
	"movetopriortab": ("browseMode", "BrowseModeTreeInterceptor", "previousTab", "Move to the previous tab"),
	"movetonextslider": ("browseMode", "BrowseModeTreeInterceptor", "nextSlider", "Move to the next slider"),
	"movetopriorslider": (
		"browseMode",
		"BrowseModeTreeInterceptor",
		"previousSlider",
		"Move to the previous slider",
	),
	"movetonextmathelement": (
		"browseMode",
		"BrowseModeTreeInterceptor",
		"nextMath",
		"Move to the next math formula",
	),
	"movetopriormathelement": (
		"browseMode",
		"BrowseModeTreeInterceptor",
		"previousMath",
		"Move to the previous math formula",
	),
	"movetonextobject": (
		"browseMode",
		"BrowseModeTreeInterceptor",
		"nextEmbeddedObject",
		"Move to the next embedded object",
	),
	"movetopriorobject": (
		"browseMode",
		"BrowseModeTreeInterceptor",
		"previousEmbeddedObject",
		"Move to the previous embedded object",
	),
	"saynextparagraph": (
		"browseMode",
		"BrowseModeTreeInterceptor",
		"nextTextParagraph",
		"Move to the next paragraph of text and read it",
	),
	"saypriorparagraph": (
		"browseMode",
		"BrowseModeTreeInterceptor",
		"previousTextParagraph",
		"Move to the previous paragraph of text and read it",
	),
	"steptostartofelement": (
		"browseMode",
		"BrowseModeDocumentTreeInterceptor",
		"moveToStartOfContainer",
		"Move to the start of the containing element, such as a list or table",
	),
	"steptoendofelement": (
		"browseMode",
		"BrowseModeDocumentTreeInterceptor",
		"movePastEndOfContainer",
		"Move past the end of the containing element, such as a list or table",
	),
}

# JAWS script name -> target for keystrokes that are not quick navigation keys (see isQuickNavKey), where
# the QUICK_NAV_MAP target would do something else. JAWS's SayNextParagraph (Caps Lock+Control+O in the
# Laptop layout) moves to the next paragraph of any kind; NVDA's quick navigation "text paragraph" (p)
# skips paragraphs that don't end like sentences, so only the P quick navigation key keeps that target.
COMMAND_KEY_TARGETS = {
	"saynextparagraph": (
		"cursorManager",
		"CursorManager",
		"moveByParagraph_forward",
		"Move to the next paragraph and read it (browse mode documents)",
	),
	"saypriorparagraph": (
		"cursorManager",
		"CursorManager",
		"moveByParagraph_back",
		"Move to the previous paragraph and read it (browse mode documents)",
	),
}

# Extra targets bound together with the primary one: JAWS script name -> tuple of targets. Empty for now.
# NVDA's editable text versions of commands (editableText.EditableText's caret_nextSentence...) are not
# usable here: they send the pressed keystroke on to the application (see SENDS_KEYSTROKE_CLASSES).
ADDITIONAL_TARGETS = {}

# NVDA scripts that pass the pressed keystroke on to the application (gesture.send()), at least in some
# cases. Bound to a JAWS keystroke they would send that keystroke, NVDA key included: in an edit field
# Caps Lock+Y bound to caret_previousSentence turns Caps Lock on and types "Y". getNvdaTargets() never
# returns them. Checked against NVDA 2026.2: every caret script of editableText.EditableText sends the
# key first unless the control declares sentence support (only Word's object model does), and the
# browse mode scripts below pass their key on.
SENDS_KEYSTROKE_CLASSES = frozenset({("editableText", "EditableText")})
SENDS_KEYSTROKE_SCRIPTS = frozenset(
	{
		("browseMode", "BrowseModeTreeInterceptor", "passThrough"),
		("browseMode", "BrowseModeTreeInterceptor", "disablePassThrough"),
		("browseMode", "BrowseModeDocumentTreeInterceptor", "collapseOrExpandControl"),
		("browseMode", "BrowseModeDocumentTreeInterceptor", "tab"),
		("browseMode", "BrowseModeDocumentTreeInterceptor", "shiftTab"),
		("cursorManager", "CursorManager", "copyToClipboard"),
	},
)


def sendsKeystroke(module: str, className: str, script: str) -> bool:
	"""Whether an NVDA script passes the keystroke that ran it on to the application."""
	return (module, className) in SENDS_KEYSTROKE_CLASSES or (module, className, script) in SENDS_KEYSTROKE_SCRIPTS


# JAWS scripts that send a standard Windows key through and speak the result. NVDA handles those keys
# natively, so bindings of plain Windows keys to these scripts need no NVDA gesture.
# Laptop bindings such as JAWSKey+U=SayPriorLine are not pass-through (see isPassThroughBinding).
PASSTHROUGH_SCRIPTS = frozenset(
	{
		# Caret movement and reading.
		"saynextcharacter",
		"saypriorcharacter",
		"saynextline",
		"saypriorline",
		"saynextword",
		"saypriorword",
		"controldownarrow",
		"controluparrow",
		"topoffile",
		"bottomoffile",
		"jawshome",
		"jawsend",
		"jawspageup",
		"jawspagedown",
		"saynextcharacterpccursor",
		"saypriorcharacterpccursor",
		"saynextlinepccursor",
		"saypriorlinepccursor",
		"saynextwordpccursor",
		"saypriorwordpccursor",
		"controldownarrowpccursor",
		"controluparrowpccursor",
		"jawshomepccursor",
		"jawsendpccursor",
		"jawspageuppccursor",
		"jawspagedownpccursor",
		# Selection.
		"selectnextcharacter",
		"selectpriorcharacter",
		"selectnextword",
		"selectpriorword",
		"selectnextline",
		"selectpriorline",
		"selectnextparagraph",
		"selectpriorparagraph",
		"selectfromstartofline",
		"selecttoendofline",
		"selectnextscreen",
		"selectpriorscreen",
		"selectfromtop",
		"selecttobottom",
		"selectall",
		"selectcurrentitem",
		# Editing and clipboard.
		"jawsbackspace",
		"jawsdelete",
		"controlbackspace",
		"undo",
		"cuttoclipboard",
		"copyselectedtexttoclipboard",
		"pastefromclipboard",
		# Windows, dialogs and controls.
		"tab",
		"shifttab",
		"enter",
		"shiftenter",
		"controlenter",
		"controlshiftenter",
		"upalevel",
		"altenterkey",
		"openlistbox",
		"closelistbox",
		"nextdocumentwindow",
		"previousdocumentwindow",
		"nextdocumentwindowbypage",
		"previousdocumentwindowbypage",
		"closedocumentwindow",
		"windowsuparrow",
		"windowsdownarrow",
		"windowsleftarrow",
		"windowsrightarrow",
		"switchinputlanguage",
		"switchinputlanguageandkeyboardlayout",
		"scrolllockkey",
		"startmenu",
		"activatesearchbox",
		"f1",
		"f3script",
		"shiftf3script",
		# Virtual cursor keys that NVDA's browse mode handles itself.
		"virtualspacebar",
		"virtualcontextmenu",
	},
)


def getNvdaTargets(scriptName: str, jawsKey: str | None = None) -> tuple[tuple[str, str, str, str], ...]:
	"""Return every NVDA ``(module, class, script, description)`` target for a JAWS script, primary first.
	:param scriptName: A JAWS script name in any case, optionally with arguments, e.g. ``"SayLine"``.
	:param jawsKey: The keystroke the script is bound to, when known. A keystroke that is not a quick
		navigation key gets the ``COMMAND_KEY_TARGETS`` target where there is one.
	:return: An empty tuple if NVDA has no equivalent. Scripts that would send the keystroke on to the
		application (see ``sendsKeystroke``) are never returned.
	"""
	name = normalizeScriptName(scriptName)
	primary = None
	if jawsKey is not None and name in COMMAND_KEY_TARGETS and not isQuickNavKey(jawsKey):
		primary = COMMAND_KEY_TARGETS[name]
	if primary is None:
		primary = SCRIPT_MAP.get(name) or QUICK_NAV_MAP.get(name)
	if primary is None:
		return ()
	targets = (primary,) + tuple(ADDITIONAL_TARGETS.get(name, ()))
	return tuple(target for target in targets if not sendsKeystroke(*target[:3]))


def isPassThroughBinding(jawsKey: str, scriptName: str) -> bool:
	"""True if this binding only passes a standard Windows key through, which NVDA handles natively.
	Bindings that use the JAWS key (for example ``JAWSKey+U=SayPriorLine`` in the laptop layout) are
	JAWS commands, not pass-through keys, so they return False. So are letter, digit and punctuation
	keys without Control or Windows, such as the Classic Laptop layout's ``Alt+L=SayNextWord``: Windows
	gives those keys to the application to type or to use as access keys.
	"""
	if normalizeScriptName(scriptName) not in PASSTHROUGH_SCRIPTS:
		return False
	key = (jawsKey or "").strip().rstrip("*")
	if not key or "&" in key or key.lower().startswith("braille"):
		return False
	tokens = [t.replace(" ", "").lower() for t in key.split("+")]
	if set(tokens) & JAWS_MODIFIER_TOKENS:
		return False
	mainKey = KEY_NAMES.get(tokens[-1], tokens[-1])
	modifiers = {KEY_NAMES.get(token, token) for token in tokens[:-1]}
	return not (len(mainKey) == 1 and not modifiers & {"control", "windows"})


def readJkmFile(path: str) -> str:
	"""Read a .jkm file. JAWS keymaps are usually ANSI; UTF-8 and UTF-16 files with a BOM are handled."""
	with open(path, "rb") as f:
		data = f.read()
	if data.startswith((b"\xff\xfe", b"\xfe\xff")):
		return data.decode("utf-16")
	if data.startswith(b"\xef\xbb\xbf"):
		return data.decode("utf-8-sig")
	try:
		return data.decode("utf-8")
	except UnicodeDecodeError:
		return data.decode("cp1252", errors="replace")


def parseJkm(text: str) -> list[tuple[str, str, str]]:
	"""Parse .jkm text into ``(section, key, script)`` tuples in file order.
	Comments (``;``) are skipped. Section names and scripts keep their original case,
	and script arguments such as ``(1)`` are kept (see normalizeScriptName).
	"""
	bindings = []
	section = ""
	for rawLine in text.splitlines():
		line = rawLine.strip()
		if not line or line.startswith(";"):
			continue
		if line.startswith("[") and line.endswith("]") and "=" not in line:
			section = line[1:-1].strip()
			continue
		if "=" not in line:
			continue
		key, script = line.split("=", 1)
		key = key.strip()
		if script.startswith("=") and (not key or key.endswith("+")):
			# The key itself is "=", for example "Shift+==AddButton".
			key += "="
			script = script[1:]
		bindings.append((section, key, script.strip()))
	return bindings
